### ISSUE TITLE
fails with non Latin symbols (Cyrillic, for example)

### ISSUE THREAD

**Issue by alexandrim0** [congnghia0609/ntc_dcrypto#2]
`
import 'package:ntcdcrypto/ntcdcrypto.dart';

void main() {
  const secret = "бар"; // wrong decoded
  // const secret = "бор"; // fails decode
  final sss = SSS();
  final shards = sss.create(2, 3, secret, true);

  print("secret.length: ${secret.length}, secret: $secret");
  print(shards);

  var s1 = sss.combine(shards.sublist(0, 2), true);
  print("secret.length: ${s1.length}, secret: $s1");

  var s2 = sss.combine(shards.sublist(1), true);
  print("secret.length: ${s2.length}, secret: $s2");

  var s3 = sss.combine(shards, true);
  print("secret.length: ${s3.length}, secret: $s3");
}
`

**Comment by congnghia0609** [comment]
This bug fixed with ntcdcrypto version 0.3.0
